[package]
name = "x402"
version = "0.1.0"
edition = "2024"

[dependencies]

# Optional Dependecies
axum = { version = "^0.8.8", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.146"
base64 = "0.22.1"
reqwest = { version = "0.12.27", features = ["json"] }

[features]
default=[]
axum  = ["dep:axum"]
