name: Check Go
on: [pull_request]

jobs:
  check-format-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: ./go/go.sum

      - name: Check formatting
        run: |
          make deps-dev
          make format-check

  lint-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: ./go/go.sum

      - name: Run golangci-lint
        run: |
          make deps-dev
          make lint-check

  test-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: ./go/go.sum

      - name: Run tests
        run: make test

  format-go-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: ./go/go.sum

      - name: Check format in Go examples
        run: make -C examples/go format-check

  lint-go-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: ./go/go.sum

      - name: Lint Go examples
        run: make -C examples/go lint-check

  build-go-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: ./go/go.sum

      - name: Build Go examples
        run: make -C examples/go build-all

